import Instance from './instance';

export default {
  signup: (data) => Instance.post('/auth/signup', data),
  login: (data) => Instance.post('/auth/login', data),
  Venues: (data) => Instance.post('/venue/create', data),
  getDataById: (id) => Instance.get(`/venue/${id}`),
  getCompanyById: (id) => Instance.get(`/company/list/${id}`),
  getVenuesData: () => Instance.get('/venue/list'),
  getCompanyData: () => Instance.get('/company/list'),
  patchVenueData: (id, data) => Instance.patch(`/venue/update/${id}`, data),
  patchCompanyData: (id, data) => Instance.patch(`company/update/${id}`, data),
  deleteVenueData: (id) => Instance.delete(`/venue/delete/${id}`),
  deleteCompanyData: (id) => Instance.delete(`/company/delete/${id}`),
  Company: (data) => Instance.post('/company', data),
  Event: (data) => Instance.post('/events', data),
  approveCompany: (id) => Instance.post(`/company/approve/${id}`),
  logout: () => Instance.post('/auth/logOut'),
  getData: (id) => Instance.get(`/permission/${id}`),
  getDesignation: () => Instance.get('/designation'),
  updateData: (id, data) => Instance.patch(`/permission/${id}`, data),
  getPermissionById: (id) => Instance.get(`/permission/list/${id}`),
  getDesignationById: (id) => Instance.get(`/designation/${id}`),
  setData: () => Instance.get('/permission/profile'),
  getEvents: () => Instance.get('/events/all'),
  editEventsData: () => Instance.patch('/'),
  getEventsData: (id) => Instance.get(`/events/${id}`),
  getAllVenues: () => Instance.get('/events/getall'),
  Bookings: (data, id) => Instance.post(`/bookings/${id}`, data),
  BookingsBraintree: () => Instance.get('/bookings/token'),
  // BookingsList: (url) => Instance.get(url),
  Payments: (paymentData) => Instance.post('/bookings/payment', paymentData),
  getBookingsData: (url) => Instance.get(url),
  getSearchData: (word) => Instance.post('/search', word),
};
